# Generated by Django 3.2.23 on 2023-12-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipsAndTricks',
            new_name='FAQ',
        ),
    ]
