# Generated by Django 3.2.23 on 2024-03-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(choices=[('Return', 'Return'), ('Item Not Delivered', 'Item Not Delivered'), ('Other', 'Other')], max_length=25),
        ),
    ]
