# Generated by Django 3.2.24 on 2024-03-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tips_and_tricks', '0002_auto_20231219_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipsandtricks',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
